# Generated by Django 5.1.2 on 2024-10-23 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricealert',
            options={'verbose_name': 'Alerta de Precio', 'verbose_name_plural': 'Alerta de Precios'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='pricealert',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pricealert',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pricealert',
            name='target_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='current_price',
        ),
        migrations.AddField(
            model_name='pricealert',
            name='alert_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de la alerta'),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio actual'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.CharField(choices=[('AliExpress', 'Aliexpress'), ('Walmart', 'Walmart')], default='AliExpress', max_length=50, verbose_name='Tienda'),
        ),
        migrations.AddField(
            model_name='product',
            name='target_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio objetivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(verbose_name='Enlace del producto'),
        ),
    ]
